# Generated by Django 4.0 on 2022-01-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your story.', max_length=300)),
                ('content', models.TextField(blank=True, help_text='Describe the story. This field is optional.')),
                ('is_available', models.BooleanField(default=True, help_text='Is this for everyone.')),
                ('author', models.CharField(blank=True, help_text='Who is the owner of the story. This field is optional.', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.CharField(blank=True, help_text='Copy the video link and paste it here. Optional field.', max_length=2000)),
                ('thumbnail', models.CharField(blank=True, help_text='Copy the image link and paste it here. Optional field.', max_length=2000)),
                ('publisher', models.ForeignKey(help_text='Who is publishing the story.', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-date'],
            },
        ),
    ]
