# Generated by Django 4.0 on 2022-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.CharField(blank=True, help_text='Copy the image link and paste it here. Optional field.', max_length=2000),
        ),
    ]
