# Generated by Django 4.0 on 2022-01-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the title?.', max_length=300)),
                ('content', models.TextField(help_text='Write the content.')),
                ('image_url', models.CharField(blank=True, help_text='Optional field', max_length=2000)),
                ('is_available', models.BooleanField(default=True, help_text='Is this for everyone.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text="The author's name.", on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Tips',
                'ordering': ['-date'],
            },
        ),
    ]
